=== hmcts/cpp-context-subscriptions/subscriptions-event/subscriptions-event-processor/src/yaml/json/schema/public.events.hearing.hearing-resulted.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/hearing/courts/public.events.hearing.hearing-resulted.json",
  "type": "object",
  "properties": {
    "hearing": {
      "$ref": "http://justice.gov.uk/core/courts/hearing.json#"
    },
    "isReshare": {
      "type": "boolean"
    },
    "sharedTime": {
      "format": "date-time"
    },
    "shadowListedOffences": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
      }
    },
    "hearingDay": {
      "$ref": "http://justice.gov.uk/core/courts/courtsDefinitions.json#/definitions/datePattern"
    }
  },
  "required": [
    "isReshare",
    "hearing",
    "sharedTime",
    "hearingDay"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-subscriptions/subscriptions-integration-test/src/test/resources/stub-data/public.events.hearing.hearing-resulted.json
{
  "hearing": {
    "id": "01234567-1234-1234-1234-123456789123",
    "type": {
      "id": "01234567-1234-1234-1234-123456789123",
      "description": "Sentence"
    },
    "jurisdictionType": "MAGISTRATES",
    "reportingRestrictionReason": "a",
    "hearingLanguage": "ENGLISH",
    "hearingDays": [
      {
        "sittingDay": "2015-01-12T05:27:17.210Z",
        "listingSequence": 0,
        "listedDurationMinutes": 0
      }
    ],
    "courtCentre": {
      "id": "COURT_CENTRE_ID",
      "name": "a",
      "welshName": "a",
      "roomId": "00000000-0000-0000-0000-000000000000",
      "roomName": "a",
      "welshRoomName": "a"
    },
    "judiciary": [
      {
        "judicialId": "00000000-0000-0000-0000-000000000000",
        "title": "a",
        "firstName": "a",
        "middleName": "a",
        "lastName": "a",
        "judicialRoleType": {
          "judicialRoleTypeId": "433a9f33-12fd-455c-bc2f-a1cb4c5692cb",
          "judiciaryType": "RECORDER"
        },
        "isDeputy": true,
        "isBenchChairman": true
      }
    ],
    "prosecutionCases": [
      {
        "id": "CASE_ID",
        "prosecutionCaseIdentifier": {
          "prosecutionAuthorityId": "00000000-0000-0000-0000-000000000000",
          "prosecutionAuthorityCode": "a",
          "caseURN": "CASE_URN"
        },
        "originatingOrganisation": "a",
        "cpsOrganisation": "A02",
        "initiationCode": "J",
        "caseStatus": "a",
        "statementOfFacts": "a",
        "statementOfFactsWelsh": "a",
        "defendants": [
          {
            "id": "111388de-c4f4-4fb5-a9be-0a0b1e374dc5",
            "masterDefendantId": "111388de-c4f4-4fb5-a9be-0a0b1e374dc5",
            "courtProceedingsInitiated": "2020-01-12T05:27:17.210Z",
            "prosecutionCaseId": "CASE_ID",
            "numberOfPreviousConvictionsCited": 0,
            "prosecutionAuthorityReference": "a",
            "witnessStatement": "a",
            "witnessStatementWelsh": "a",
            "mitigation": "a",
            "mitigationWelsh": "a",
            "defendantCaseJudicialResults":[
              {
                "alwaysPublished":false,
                "category":"FINAL",
                "cjsCode":"3011",
                "courtClerk":{
                  "firstName":"Erica",
                  "lastName":"Wilson",
                  "userId":"a085e359-6069-4694-8820-7810e7dfe762"
                },
                "d20":false,
                "excludedFromResults":false,
                "isAdjournmentResult":false,
                "isAvailableForCourtExtract":true,
                "isConvictedResult":true,
                "isDeleted":false,
                "isFinancialResult":true,
                "judicialResultId":"edeeba78-8f38-410c-bf87-483acaaae7b2",
                "judicialResultPrompts":[
                  {
                    "courtExtract":"Y",
                    "isFinancialImposition":true,
                    "judicialResultPromptTypeId":"f63b0bb5-7d93-4dab-bc3d-b4bd27152871",
                    "label":"Amount of costs",
                    "promptReference":"AOC",
                    "promptSequence":100,
                    "type":"CURR",
                    "usergroups":[

                    ],
                    "value":"£60",
                    "welshLabel":""
                  }
                ],
                "judicialResultTypeId":"f5d492b8-a09b-4f70-9ceb-aa06c306a7dc",
                "label":"Costs to Crown Prosecution Service",
                "lastSharedDateTime":"2020-06-11",
                "lifeDuration":false,
                "orderedDate":"2020-06-11",
                "orderedHearingId":"85751204-4c05-4fa8-970f-8b1ffc4b94ec",
                "postHearingCustodyStatus":"A",
                "publishedAsAPrompt":false,
                "publishedForNows":false,
                "rank":10800,
                "resultText":"Costs to Crown Prosecution Service\nAmount of costs £60",
                "resultWording":"Cost of Crown from result wording \nAmount of costs £70",
                "rollUpPrompts":true,
                "terminatesOffenceProceedings":false,
                "urgent":false,
                "usergroups":[

                ],
                "welshLabel":"Costau i Wasanaeth Erlyn y Goron"
              }
            ],
            "offences": [
              {
                "id": "1bed87c6-f1fd-46ca-9f7e-d74d0142a613",
                "offenceDefinitionId": "00000000-0000-0000-0000-000000000000",
                "offenceCode": "a",
                "offenceTitle": "a",
                "offenceTitleWelsh": "a",
                "offenceLegislation": "a",
                "offenceLegislationWelsh": "a",
                "modeOfTrial": "a",
                "wording": "a",
                "wordingWelsh": "a",
                "reportingRestrictions": [
                  {
                    "id": "1bed87c6-f1fd-46ca-9f7e-d74d0142a613",
                    "judicialResultId": "dfbb575d-6b88-489f-9f90-f960bfafa742",
                    "label": "Order made under Section 11 of the Contempt of Court Act 1981",
                    "orderedDate": "2021-08-30"
                  }
                ],
                "startDate": "2018-01-01",
                "endDate": "2018-01-01",
                "arrestDate": "2018-01-01",
                "chargeDate": "2018-01-01",
                "dateOfInformation": "2018-01-01",
                "orderIndex": 0,
                "count": 0,
                "convictionDate": "2018-01-01",
                "notifiedPlea": {
                  "offenceId": "00000000-0000-0000-0000-000000000000",
                  "notifiedPleaDate": "2018-01-01",
                  "notifiedPleaValue": "NOTIFIED_GUILTY"
                },
                "indicatedPlea": {
                  "offenceId": "00000000-0000-0000-0000-000000000000",
                  "indicatedPleaDate": "2018-01-01",
                  "indicatedPleaValue": "INDICATED_GUILTY",
                  "source": "ONLINE"
                },
                "plea": {
                  "originatingHearingId": "00000000-0000-0000-0000-000000000000",
                  "delegatedPowers": {
                    "userId": "00000000-0000-0000-0000-000000000000",
                    "firstName": "a",
                    "lastName": "a"
                  },
                  "offenceId": "00000000-0000-0000-0000-000000000000",
                  "pleaDate": "2018-01-01",
                  "pleaValue": "GUILTY"
                },
                "verdict": {
                  "originatingHearingId": "00000000-0000-0000-0000-000000000000",
                  "offenceId": "00000000-0000-0000-0000-000000000000",
                  "verdictDate": "2018-01-01",
                  "verdictType": {
                    "id": "00000000-0000-0000-0000-000000000000",
                    "sequence": 0,
                    "description": "a",
                    "category": "a",
                    "categoryType": "a"
                  },
                  "jurors": {
                    "numberOfJurors": 1,
                    "numberOfSplitJurors": 1,
                    "unanimous": true
                  },
                  "lesserOrAlternativeOffence": {
                    "offenceDefinitionId": "00000000-0000-0000-0000-000000000000",
                    "offenceCode": "a",
                    "offenceTitle": "a",
                    "offenceTitleWelsh": "a",
                    "offenceLegislation": "a",
                    "offenceLegislationWelsh": "a"
                  }
                },
                "offenceFacts": {
                  "vehicleRegistration": "a",
                  "alcoholReadingAmount": 123
                },
                "judicialResults": [
                  {
                    "orderedHearingId": "00000000-0000-0000-0000-000000000000",
                    "judicialResultId": "94d6e18a-4114-11ea-b77f-2e728ce88125",
                    "judicialResultTypeId": "94d6e432-4114-11ea-b77f-2e728ce88125",
                    "label": "a",
                    "welshLabel": "a",
                    "isAdjournmentResult": true,
                    "isFinancialResult": true,
                    "isConvictedResult": true,
                    "isAvailableForCourtExtract": true,
                    "amendmentDate": "0000-01-01",
                    "amendmentReason": "a",
                    "cjsCode": "a",
                    "rank": 0.1,
                    "orderedDate": "2020-01-01",
                    "lastSharedDateTime": "a",
                    "courtClerk": {
                      "userId": "00000000-0000-0000-0000-000000000000",
                      "firstName": "a",
                      "lastName": "a"
                    },
                    "delegatedPowers": {
                      "userId": "00000000-0000-0000-0000-000000000000",
                      "firstName": "a",
                      "lastName": "a"
                    },
                    "fourEyesApproval": {
                      "userId": "00000000-0000-0000-0000-000000000000",
                      "firstName": "a",
                      "lastName": "a"
                    },
                    "approvedDate": "0000-01-01",
                    "usergroups": [
                      "a"
                    ],
                    "category": "FINAL",
                    "terminatesOffenceProceedings": false,
                    "lifeDuration" : false,
                    "rollUpPrompts": false,
                    "publishedForNows" : false,
                    "publishedAsAPrompt" : false,
                    "excludedFromResults" : false,
                    "alwaysPublished" : false,
                    "urgent" : false,
                    "d20" : false,
                    "resultText" : "code - resultText",
                    "resultWording": "resultWording",
                    "judicialResultPrompts": [
                      {
