=== hmcts/cpp-context-subscriptions/subscriptions-event/subscriptions-event-processor/src/yaml/json/schema/public.hearing.trial-vacated.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/hearing/courts/trial-vacated.json",
  "type": "object",
  "properties": {
    "hearingId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "vacatedTrialReasonId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "hearingDateTime": {
      "type": "string",
      "format": "date-time"
    },
    "hasInterpreter": {
      "type": "boolean"
    },
    "caseDetails": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "#/definitions/hearingCaseDetail"
      }
    },
    "applicationDetails": {
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "#/definitions/applicationDetail"
      }
    },
    "jurisdictionType": {
      "$ref": "http://justice.gov.uk/core/courts/jurisdictionType.json"
    }
  },
  "required": [
    "hearingId"
  ],
  "additionalProperties": false,
  "definitions": {
    "hearingCaseDetail": {
      "type": "object",
      "properties": {
        "caseId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "caseURN": {
          "type": "string"
        },
        "defendantDetails": {
          "type": "array",
          "minItems": 0,
          "items": {
            "defendantId": {
              "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
            },
            "defendantFirstName": {
              "type": "string"
            },
            "defendantLastName": {
              "type": "string"
            },
            "defendantRemandStatus": {
              "type": "string"
            },
            "interpreterLanguageNeeds": {
              "type": "string"
            }
          }
        }
      }
    },
    "applicationDetail": {
      "type": "object",
      "properties": {
        "applicationId": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "applicationReference": {
          "type": "string"
        },
        "subject": {
          "type": "object",
          "properties": {
            "defendantId": {
              "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
            },
            "defendantFirstName": {
              "type": "string"
            },
            "defendantLastName": {
              "type": "string"
            },
            "defendantRemandStatus": {
              "type": "string"
            },
            "interpreterLanguageNeeds": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== hmcts/cpp-context-subscriptions/subscriptions-integration-test/src/test/resources/stub-data/public.hearing.trial-vacated.json
{
  "hearingId": "%HEARING_ID%",
  "vacatedTrialReasonId": "12ff072c-c287-11e9-9cb5-2a2ae2d9cce0",
  "hasInterpreter": false,
  "hearingDateTime": "2022-08-24T01:46:36.068Z",
  "caseDetails": [
    {
      "caseId": "22ff0722-c287-11e9-9cb5-2a2ae2dbcce4",
      "caseUrn": "TFL122222",
      "defendantDetails": [
        {
          "defendantId":"32ff0722-c287-11e9-9cb5-2a2ae2dbcce4",
          "defendantFirstName": "Abbie",
          "defendantLastName": "ARMSTRONG",
          "defendantRemandStatus": "status",
          "interpreterLanguageNeeds": "Hindi"
        }
      ]
    }
  ],
  "applicationDetails": [
    {
      "applicationId": "32ff0722-c287-11e9-9cb5-2a2ae2dbcce4",
      "applicationReference": "TFL34652354",
      "subject": {
        "defendantId":"42ff0722-c287-11e9-9cb5-2a2ae2dbcce4",
        "defendantFirstName": "John",
        "defendantLastName": "DOE",
        "defendantRemandStatus": "status",
        "interpreterLanguageNeeds": "Hindi"
      }
    }
  ]
}
