=== hmcts/cpp-context-subscriptions/subscriptions-domain/subscriptions-domain-value-schema/src/main/resources/json/schema/subscription.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/subscriptions/json/schemas/subscription.json",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "name": {
      "type": "string"
    },
    "nowsOrEdts": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0
    },
    "events": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/subscriptions/json/schemas/enum-def.json#/definitions/events"
      },
      "minItems": 0
    },
    "subscribers": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/subscriptions/json/schemas/subscribers.json"
      }
    },
    "active": {
      "type": "boolean"
    },
    "filter": {
        "$ref": "http://cpp.moj.gov.uk/subscriptions/json/schemas/filter.json"
    },
    "courts": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/subscriptions/json/schemas/court.json"
      },
      "minItems": 1,
      "maxItems": 5
    }
  },
  "additionalProperties": false
}

=== hmcts/cpp-context-subscriptions/subscriptions-integration-test/src/test/resources/stub-data/create-subscription-command.json
{
  "id": "%ID%",
  "name": "Derby Only",
  "nowsOrEdts": [
    "Custody Warrant on Discharge of Extradition Pending Appeal",
    "Custody Warrant on Extradition"
  ],
  "events": [
    "CRACKED_OR_INEFFECTIVE_TRAIL",
    "CHANGE_OF_PLEA",
    "REMAND_STATUS",
    "DEFENDANT_APPELLANT_ATTENDANCE",
    "PLEAS_ENTER",
    "VERDICTS_ENTER",
    "PRE_SENTENCE_REPORT_REQUESTED"
  ],
  "subscribers": [
      "deby@thirdparty.com"
  ],
  "filter": {
    "filterType": "CASE_REFERENCE",
    "urn": "324135134"
  },
  "courts": [
    {
      "courtId": "3803e612-6369-461a-a2cc-25abb374c5cc",
      "name": "Derby Court House"
    }
  ]
}

=== hmcts/cpp-context-subscriptions/subscriptions-event/subscriptions-event-processor/src/test/resources/stub/CreateSubscriptionForSpecificSubscriberCommand.json
{
  "id": "4a0e892d-c0c5-3c51-95b8-704d8c781771",
  "name": "Derby Only",
  "nowsOrEdts": [
    "Custody Warrant on Extradition"
  ],
  "events": [
    "PLEAS_ENTER"
  ],
  "subscribers": [
    {
      "active" :true,
      "emailAddress" :"richard.chapman@acme.com",
      "id": "4a0e892d-c0c5-3c51-95b8-704d8c781772"
    }

  ],
  "filter": {
    "filterType": "CASE_REFERENCE",
    "urn": "URN123"
  },
  "courts": [
    {
      "courtId": "3803e612-6369-461a-a2cc-25abb374c5cc",
      "name": "Derby Court House"
    }
  ],
  "active": true
}

=== hmcts/cpp-context-subscriptions/subscriptions-integration-test/src/test/resources/stub-data/create-subscription-command-for-cracked-or-ineffective-trial.json
{
  "id": "%ID%",
  "name": "Derby Only",
  "nowsOrEdts": [
    "Custody Warrant on Discharge of Extradition Pending Appeal",
    "Custody Warrant on Extradition"
  ],
  "events": [
    "CRACKED_OR_INEFFECTIVE_TRAIL"
  ],
  "subscribers": [
    "deby@thirdparty.com"
  ],
  "filter": {
    "filterType": "CASE_REFERENCE",
    "urn": "%CASE_URN%"
  },
  "courts": [
    {
      "courtId": "%COURT_ID%",
      "name": "Derby Court House"
    }
  ]
}
